INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'plocivoj@fel.cvut.cz', 'Vojtěch', 'Plocica', null, '$2a$10$pqPVbKjs8dm9RT6rKoCmLO5AxoyilSLeamO/qDY86So6w7Cj9F0XK', null, 'REGULAR_USER', 'plocivoj');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'belkapre@fel.cvut.cz', 'Přemek', 'Bělka', null, '$2a$10$smEBn5slEsVNJ6NOQuj3Wu1arANgFR//5U537f/lAGXlgiXNLFRey', null, 'REGULAR_USER', 'belkapre');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'szelemar@fel.cvut.cz', 'Marek', 'Szeles', null, '$2a$10$SV/1sYjcp3wlyEGjUUlI5e51g3UIp3Jo37c.hyPo0oimXSHcy2/m.', null, 'REGULAR_USER', 'szelemar');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'brabeja6@fel.cvut.cz', 'Jan', 'Brabec', null, '$2a$10$Z0Ao.nptbd42JUTA..pPseGFG22kXE3lOe6Q.U.RZDPBbGRG/ulBO', null, 'REGULAR_USER', 'brabeja6');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'havlicr@fel.cvut.cz', 'Radek', 'Havlíček', null, '$2a$10$YH5s4JVe7Wp20H13tRWKiexDzGcBchXJ38JiGhzJq2MJ/AqRtDJla', null, 'REGULAR_USER', 'havlicr');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'nagyoing@fel.cvut.cz', 'Ingrid', 'Nagyová', null, '$2a$10$E6F8/5pGI7YUywWDON0..Oa8F78HUzxkbVz.cJplw6FJyimF49o3G', null, 'REGULAR_USER', 'nagyoing');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'richta@fel.cvut.cz', 'Karel', 'Richta', null, '$2a$10$doUuCY7WVzC94WFZWYG7L.6gl3l5S4rNEy7vBNvMCKxG93ycYI7ha', null, 'REGULAR_USER', 'richta');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'jiri.kaspar@fit.cvut.cz', 'Jiří', 'Kašpar', null, '$2a$10$Cab1MHMZHIdjQADzs6wNQuXt/WJR7oeMreqRcsoG1ICqh76vN..Ra', null, 'REGULAR_USER', 'kaspaji3');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'jerabma7@fel.cvut.cz', 'Martin', 'Jeřábek', null, '$2a$10$KPrT6QZ1dMYLLPD.mB9MbeBaKQAf5KQXXhqueCGvut3SyAjIZYn2O', null, 'REGULAR_USER', 'jerabma7');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'kukacdav@fit.cvut.cz', 'David', 'Kukačka', null, '$2a$10$0Uav6yfDMzAMfXkvUdMr1.DZf69qkHZKCBmBhVy0cSKsbGdjDWY.i', null, 'REGULAR_USER', 'kukacdav');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'zidekja2@fel.cvut.cz', 'Jan', 'Zídek', null, '$2a$10$8XQkU/tS.ojgS4QCs38To.lb4fTPFLvCyHYtm7LI3o2k.ZaBE9NWy', null, 'REGULAR_USER', 'zidekja2');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'sebekji1@fel.cvut.cz', 'Jiří', 'Šebek', null, '$2a$10$XXXx.o9V3LRTC46yhtIzY.oISw.smSao43VcrgsmI77twrFfNffoi', null, 'REGULAR_USER', 'sebekji1');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'kadlecd@fel.cvut.cz', 'David', 'Kadleček', null, '$2a$10$Tvr50R9cnXbZvv9GukKr1OUge1vvXn2unGHey7pWGg3mslryw2B5e', null, 'REGULAR_USER', 'kadlecd');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'ledvima1@fel.cvut.cz', 'Martin', 'Ledvinka', null, '$2a$10$QD7LLDB0IE9pZ4JV5hZSkeXKxnvH6ROELaeBqEAW2CElvwJRpqFZS', null, 'REGULAR_USER', 'ledvima1');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'rimnacm@fel.cvut.cz', 'Martin', 'Řimnáč', null, '$2a$10$L7ecr35jJaH3GQbenXG9oewDY8G6Eq3OkKsq/2UUH6bPvAWIkXIwC', null, 'REGULAR_USER', 'rimnacm');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'petr.kremen@cvut.cz', 'Petr', 'Křemen', null, '$2a$10$w/CvtSj31iU1E0Zpq0BhWOilqR9vQvGP0W0D.RmnRkFcs97cgXMIW', null, 'REGULAR_USER', 'kremep1');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'aubrech@partner.cvut.cz', 'Petr', 'Aubrecht', null, '$2a$10$JjTCe9LKFXgJa3lgGuqV3.in2B4tNTufcsTQF.rDlTn.ps2CuUh76', null, 'REGULAR_USER', 'aubrech');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'zhukavet@fel.cvut.cz', 'Natalie', 'Žukovec', null, '$2a$10$3b15rz4hwjh3D0Iym9Rmk.Dg96cPeUnyWEYK/4yYU2Fnsc3B0v5Am', null, 'REGULAR_USER', 'zhukavet');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'bohac@fel.cvut.cz', 'Leoš', 'Boháč', null, '$2a$10$p/WKIe7mFHPgWLQObyv9w.vDe.PO4ydv7VXtgufKtRfcgI9qBfaSm', null, 'REGULAR_USER', 'bohac');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'bezpalec@fel.cvut.cz', 'Pavel', 'Bezpalec', null, '$2a$10$Oyhcg3kmwdagmV3iEgnPe.5ggXSJAlMBVYQiF80FL7EXDg9z57OUS', null, 'REGULAR_USER', 'bezpalec');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'kucerj17@fel.cvut.cz', 'Ján', 'Kučerák', null, '$2a$10$IbeWC2D9BUzWuyQJr9Nbi./4hAVvOBrtUor2tQG.E4mubj9frPrDK', null, 'REGULAR_USER', 'kucerj17');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'tomas.vanek@fel.cvut.cz', 'Tomáš', 'Vaněk', null, '$2a$10$x.ygxBQMSxXjSBSEbpyZbOkpSwQajJu6ATE7a/fr8gNFi9l9Dm77K', null, 'REGULAR_USER', 'vanekt1');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'zbynek.kocur@cvut.cz', 'Zbyněk', 'Kocur', null, '$2a$10$ucvLNY5nyuXiXgZaAVy0Oe/c6qoCUh.JkHVfaFvQe5HlRS9zEuGI6', null, 'REGULAR_USER', 'kocurzby');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'josef.cernohous@cvut.cz', 'Josef', 'Černohous', null, '$2a$10$iIxdYkc.Kmfq7yDH2/BjsOBl88JKFaU7HxDL1L795H4eS3Eg/4uQC', null, 'REGULAR_USER', 'cernohj1');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'dobiam1@fel.cvut.cz', 'Martin', 'Dobiáš', null, '$2a$10$AbbjEAR5.6zUfWovKsYL3OnyyXrsMI582G1FEykvXpWr76Fu3bnRq', null, 'REGULAR_USER', 'dobiam1');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'horakm11@fel.cvut.cz', 'Martin', 'Horák', null, '$2a$10$7XqtZT0FaqOi5aUOY4sfzu2UEr5C5A1BDQ.bjl2q5udDCy05Fb7E2', null, 'REGULAR_USER', 'horakm11');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'noskovb@fel.cvut.cz', 'Blanka', 'Kučerková', null, '$2a$10$QxW1AmXrJ5AuAgC0BWGS6eaZCu/EgbUuG1C9S703/bfo4gJDvyQZS', null, 'REGULAR_USER', 'noskovb');
INSERT INTO public.system_user (id, email, first_name, last_name, mailing_address, password, permanent_residence, role, username) VALUES (default, 'vasicek@fel.cvut.cz', 'Jiří', 'Vašíček', null, '$2a$10$c2hLOxI2zGvFjAr9NpHFkOs3G7E9BTiDb9T.zLvCN8bWWXVUduc7S', null, 'REGULAR_USER', 'vasicek');

INSERT INTO public.course (id, code, completion_type, credits, description, name, recommended_semester) VALUES (default, 'B6B36EAR', 'CLFD_CREDIT', 5, null, 'Enterprise Architectures', null);
INSERT INTO public.course (id, code, completion_type, credits, description, name, recommended_semester) VALUES (default, 'B6B36PJC', 'CLFD_CREDIT', 4, null, 'Programming in C/C++', null);
INSERT INTO public.course (id, code, completion_type, credits, description, name, recommended_semester) VALUES (default, 'B6B36OMO', 'CREDIT_EXAM', 6, null, 'Object-oriented design and Modeling', null);
INSERT INTO public.course (id, code, completion_type, credits, description, name, recommended_semester) VALUES (default, 'B6B01MAA', 'CREDIT_EXAM', 5, null, 'Mathematics Analysis', null);
INSERT INTO public.course (id, code, completion_type, credits, description, name, recommended_semester) VALUES (default, 'B6B32PSI', 'CREDIT_EXAM', 5, null, 'Computer Networks', null);
INSERT INTO public.course (id, code, completion_type, credits, description, name, recommended_semester) VALUES (default, 'B6B16ZPD', 'CREDIT_EXAM', 5, null, 'Business Economics', null);
INSERT INTO public.course (id, code, completion_type, credits, description, name, recommended_semester) VALUES (default, 'B6B36RSP', 'CREDIT_EXAM', 6, null, 'Management of Software Projects', null);
INSERT INTO public.course (id, code, completion_type, credits, description, name, recommended_semester) VALUES (default, 'B6B01PST', 'CREDIT_EXAM', 4, null, 'Probability and Statistics', null);
INSERT INTO public.course (id, code, completion_type, credits, description, name, recommended_semester) VALUES (default, 'B6B36NSS', 'CREDIT_EXAM', 5, null, 'Design of Software Systems', null);
INSERT INTO public.course (id, code, completion_type, credits, description, name, recommended_semester) VALUES (default, 'B6B36DSA', 'CREDIT_EXAM', 6, null, 'Data Structures and Algorithms', null);
INSERT INTO public.course (id, code, completion_type, credits, description, name, recommended_semester) VALUES (default, 'B6B16INS', 'CLFD_CREDIT', 4, null, 'Information Systems', null);
INSERT INTO public.course (id, code, completion_type, credits, description, name, recommended_semester) VALUES (default, 'B0B39KAJ', 'CREDIT_EXAM', 5, null, 'Client applications in JavaScript', null);

INSERT INTO public.semester (id, code, state, type, year) VALUES (default, 'B211', 'CURRENT', 'WINTER', '2021');
INSERT INTO public.semester (id, code, state, type, year) VALUES (default, 'B212', 'PREPARATION', 'SUMMER', '2021');

INSERT INTO public.course_in_semester (id, course_id, semester_id) VALUES (default, 1, 1);
INSERT INTO public.course_in_semester (id, course_id, semester_id) VALUES (default, 2, 1);
INSERT INTO public.course_in_semester (id, course_id, semester_id) VALUES (default, 3, 1);
INSERT INTO public.course_in_semester (id, course_id, semester_id) VALUES (default, 4, 1);
INSERT INTO public.course_in_semester (id, course_id, semester_id) VALUES (default, 5, 1);
INSERT INTO public.course_in_semester (id, course_id, semester_id) VALUES (default, 6, 1);
INSERT INTO public.course_in_semester (id, course_id, semester_id) VALUES (default, 7, 2);
INSERT INTO public.course_in_semester (id, course_id, semester_id) VALUES (default, 8, 2);
INSERT INTO public.course_in_semester (id, course_id, semester_id) VALUES (default, 9, 2);
INSERT INTO public.course_in_semester (id, course_id, semester_id) VALUES (default, 10, 2);
INSERT INTO public.course_in_semester (id, course_id, semester_id) VALUES (default, 11, 2);
INSERT INTO public.course_in_semester (id, course_id, semester_id) VALUES (default, 12, 2);

INSERT INTO public.classroom (id, name) VALUES (default, 'T2:A4-202a');
INSERT INTO public.classroom (id, name) VALUES (default, 'T2:A4-203b');
INSERT INTO public.classroom (id, name) VALUES (default, '');
INSERT INTO public.classroom (id, name) VALUES (default, 'T2:C3-340');
INSERT INTO public.classroom (id, name) VALUES (default, 'T2:B3-714');
INSERT INTO public.classroom (id, name) VALUES (default, 'T2:C3-337');
INSERT INTO public.classroom (id, name) VALUES (default, 'T2:C3-51');
INSERT INTO public.classroom (id, name) VALUES (default, 'T2:C4-78');
INSERT INTO public.classroom (id, name) VALUES (default, 'KN:E-328');
INSERT INTO public.classroom (id, name) VALUES (default, 'KN:E-307');
INSERT INTO public.classroom (id, name) VALUES (default, 'KN:E-107');
INSERT INTO public.classroom (id, name) VALUES (default, 'KN:E-311');
INSERT INTO public.classroom (id, name) VALUES (default, 'T2:D3-309');
INSERT INTO public.classroom (id, name) VALUES (default, 'KN:E-310');
INSERT INTO public.classroom (id, name) VALUES (default, 'T2:H1-130');
INSERT INTO public.classroom (id, name) VALUES (default, 'T2:H1-131');

INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 23, 0, '14:15:00', '101', null, 'TUTORIAL', '12:45:00', 1, 6);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 0, 0, '16:00:00', '102', null, 'TUTORIAL', '14:30:00', 1, 6);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 22, 0, '14:15:00', '103', null, 'TUTORIAL', '12:45:00', 2, 6);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 23, 0, '16:00:00', '104', null, 'TUTORIAL', '14:30:00', 2, 6);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 0, 2, '14:15:00', '105', null, 'TUTORIAL', '12:45:00', 3, 6);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 75, 0, '12:30:00', '1', null, 'LECTURE', '11:00:00', 4, 6);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '09:00:00', '101', null, 'TUTORIAL', '07:30:00', 5, 5);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '10:45:00', '102', null, 'TUTORIAL', '09:15:00', 5, 5);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '12:30:00', '103', null, 'TUTORIAL', '11:00:00', 5, 5);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '14:15:00', '104', null, 'TUTORIAL', '12:45:00', 5, 5);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '16:00:00', '105', null, 'TUTORIAL', '14:30:00', 5, 5);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '17:45:00', '106', null, 'TUTORIAL', '16:15:00', 5, 5);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '19:30:00', '107', null, 'TUTORIAL', '18:00:00', 5, 5);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 200, 3, '17:45:00', '1', null, 'LECTURE', '16:15:00', 6, 5);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 25, 3, '10:45:00', '101', null, 'TUTORIAL', '09:15:00', 7, 4);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 25, 3, '12:30:00', '102', null, 'TUTORIAL', '11:00:00', 7, 4);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 25, 4, '10:45:00', '103', null, 'TUTORIAL', '09:15:00', 8, 4);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 0, 4, '12:30:00', '104', null, 'TUTORIAL', '11:00:00', 8, 4);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 110, 3, '16:00:00', '1', null, 'LECTURE', '14:30:00', 6, 4);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 2, '17:45:00', '101', null, 'TUTORIAL', '16:15:00', 9, 1);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 2, '12:30:00', '102', null, 'TUTORIAL', '11:00:00', 9, 1);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 2, '14:15:00', '103', null, 'TUTORIAL', '12:45:00', 9, 1);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 2, '19:30:00', '104', null, 'TUTORIAL', '18:00:00', 9, 1);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 0, 2, '17:45:00', '105', null, 'TUTORIAL', '16:15:00', 10, 1);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 0, 2, '19:30:00', '106', null, 'TUTORIAL', '18:00:00', 10, 1);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 200, 2, '10:45:00', '1', null, 'LECTURE', '09:15:00', 11, 1);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 0, 3, '09:00:00', '101', null, 'TUTORIAL', '07:30:00', 12, 3);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 0, 3, '10:45:00', '102', null, 'TUTORIAL', '09:15:00', 12, 3);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 21, 3, '12:30:00', '103', null, 'TUTORIAL', '11:00:00', 12, 3);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 3, '14:15:00', '104', null, 'TUTORIAL', '12:45:00', 12, 3);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '10:45:00', '105', null, 'TUTORIAL', '09:15:00', 12, 3);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 21, 1, '12:30:00', '106', null, 'TUTORIAL', '11:00:00', 12, 3);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '17:45:00', '107', null, 'TUTORIAL', '16:15:00', 9, 3);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '16:00:00', '108', null, 'TUTORIAL', '14:30:00', 9, 3);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 200, 0, '10:45:00', '1', null, 'LECTURE', '09:15:00', 13, 3);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 3, '10:45:00', '101', null, 'TUTORIAL', '09:15:00', 14, 2);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 3, '12:30:00', '102', null, 'TUTORIAL', '11:00:00', 14, 2);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 3, '14:15:00', '103', null, 'TUTORIAL', '12:45:00', 14, 2);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '10:45:00', '104', null, 'TUTORIAL', '09:15:00', 14, 2);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '12:30:00', '105', null, 'TUTORIAL', '11:00:00', 14, 2);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 0, 1, '14:15:00', '106', null, 'TUTORIAL', '12:45:00', 15, 2);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '16:00:00', '107', null, 'TUTORIAL', '14:30:00', 15, 2);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 20, 1, '17:45:00', '108', null, 'TUTORIAL', '16:15:00', 16, 2);
INSERT INTO public.parallel (id, capacity, day_of_week, end_time, name, note, parallel_type, start_time, classroom_id, course_in_semester_id) VALUES (default, 200, 2, '16:00:00', '1', null, 'LECTURE', '14:30:00', 11, 2);

INSERT INTO public.course_student (id, course_id, user_id) VALUES (1, 6, 4);
INSERT INTO public.course_student (id, course_id, user_id) VALUES (2, 6, 5);
INSERT INTO public.course_student (id, course_id, user_id) VALUES (3, 5, 4);
INSERT INTO public.course_student (id, course_id, user_id) VALUES (4, 5, 5);
INSERT INTO public.course_student (id, course_id, user_id) VALUES (5, 4, 4);
INSERT INTO public.course_student (id, course_id, user_id) VALUES (6, 4, 5);
INSERT INTO public.course_student (id, course_id, user_id) VALUES (7, 1, 4);
INSERT INTO public.course_student (id, course_id, user_id) VALUES (8, 1, 5);
INSERT INTO public.course_student (id, course_id, user_id) VALUES (9, 3, 4);
INSERT INTO public.course_student (id, course_id, user_id) VALUES (10, 3, 5);
INSERT INTO public.course_student (id, course_id, user_id) VALUES (11, 2, 4);
INSERT INTO public.course_student (id, course_id, user_id) VALUES (12, 2, 5);

INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (13, 2, 6);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (14, 2, 7);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (15, 2, 8);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (16, 2, 9);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (17, 2, 10);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (18, 2, 11);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (19, 2, 12);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (20, 3, 13);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (21, 3, 14);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (22, 3, 15);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (23, 3, 16);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (24, 1, 17);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (25, 1, 18);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (26, 1, 19);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (27, 1, 20);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (28, 4, 21);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (29, 5, 22);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (30, 5, 23);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (31, 5, 24);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (32, 5, 25);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (33, 5, 26);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (34, 6, 27);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (35, 6, 28);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (36, 6, 29);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (37, 6, 30);
INSERT INTO public.course_teacher (id, course_id, user_id) VALUES (38, 6, 31);

SELECT setval('course_participant_id_seq', 38, true);

INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (1, 1);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (1, 6);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (2, 1);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (2, 6);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (3, 11);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (3, 14);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (4, 10);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (4, 14);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (5, 15);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (5, 19);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (6, 16);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (6, 19);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (7, 20);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (7, 26);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (8, 22);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (8, 26);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (9, 30);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (9, 35);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (10, 31);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (10, 35);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (11, 43);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (11, 44);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (12, 40);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (12, 44);

INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (15, 36);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (15, 37);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (15, 38);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (16, 39);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (16, 40);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (16, 42);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (16, 43);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (17, 44);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (20, 31);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (20, 32);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (21, 29);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (21, 30);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (22, 33);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (22, 34);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (23, 35);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (24, 20);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (24, 22);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (25, 21);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (26, 26);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (27, 23);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (27, 26);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (28, 15);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (28, 16);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (28, 17);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (28, 18);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (28, 19);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (29, 14);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (30, 7);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (30, 9);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (30, 10);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (30, 12);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (31, 8);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (31, 11);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (31, 13);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (32, 14);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (35, 6);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (36, 1);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (36, 2);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (37, 3);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (37, 4);
INSERT INTO public.course_participant_parallels (course_participant_id, parallels_id) VALUES (38, 6);